name: upload my image to DockerHub

on:
  pull_request:
    branches: [main]
    types:
      - closed
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create docker image
        run: echo Hello, world!

      -name: create env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_docker_user: ${{ secrets.DOCKER_USER }}
          ENV_docker_token: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/calculator:latest

      - name: push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/calculator:latest
