name: upload my image to DockerHub

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create docker image
        run: echo Hello, world!

      - name: create env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DOCKER_USER: ${{ secrets.DOCKER_USER }}
          envkey_DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          file_name: docker.env
          directory: group_vars

      - name: run playbook
        run: |
          ansible-playbook ./ansible/main.yml --ssh-common-args='-o StrictHostKeyChecking=no'

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_TOKEN }}

      # - name: Build
      #   run: docker build . --tag ${{ secrets.DOCKER_USER }}/calculator:latest

      # - name: push to DockerHub
      #   run: docker push ${{ secrets.DOCKER_USER }}/calculator:latest
